const backgrounds = [
    require("../assets/1.jpeg"),
    require("../assets/2.jpeg"),
    require("../assets/3.jpeg"),
    require("../assets/4.jpeg"),
    require("../assets/5.jpeg"),
    require("../assets/6.jpeg"),
    require("../assets/7.jpeg"),
    require("../assets/8.jpeg"),
    require("../assets/9.jpeg"),
    require("../assets/10.jpeg"),
    require("../assets/11.jpeg"),
    require("../assets/12.jpeg"),
    require("../assets/13.jpeg"),
    require("../assets/14.jpeg"),
    require("../assets/15.jpeg"),
    require("../assets/16.jpeg"),
    require("../assets/17.jpeg"),
    require("../assets/18.jpeg"),
    require("../assets/19.jpeg"),
    require("../assets/20.jpeg"),
    require("../assets/21.jpeg"),
    require("../assets/22.jpeg"),
    require("../assets/23.jpeg"),
    require("../assets/24.jpeg"),
]

export {backgrounds};