const quotes = [
    "You meet thousands of people and none of them really touch you. And then you meet one person and your life is changed forever.",
    "We loved with a love that was more than love.",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    "I think we dream so we don't have to be apart for so long. If we're in each other's dreams, we can be together all the time.",
    "That's how you know you love someone, I guess, when you can't experience anything without wishing the other person were there to see it, too.",
    "We were together even when we were apart.",
    "I will return. I will find you. Love you. Marry you. And live without shame.",
    "There are no goodbyes for us. Wherever you are, you will always be in my heart.",
    "The pain of parting is nothing to the joy of meeting again.",
    "But I must admit, I miss you quite terribly. The world is too quiet without you nearby.",
    "We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly.",
    "You are my greatest adventure.",
    "Love isn't hopeless. Look, maybe I'm no expert on the subject, but there was one time I got it right.",
    "If I had a flower for every time I thought of you... I could walk through my garden forever.",
    "Remember, we're madly in love, so it's alright to kiss me anytime you feel like it.",
    "Yes, I'm drunk. And you're beautiful. And tomorrow morning, I'll be sober but you'll still be beautiful.",
    "Man may have discovered fire, but women discovered how to play with it.",
    "I love her and that's the beginning and end of everything.",
    "You were worth the wait, and I don't just mean tonight.",
    "The greatest thing you'll ever learn is just to love, and be loved, in return.",
    "But the you who you are tonight is the same you I was in love with yesterday, the you I'll be in love with tomorrow.",
    "That's my sweetheart in there. Wherever she is, that's where my home is.",
    "The most precious possession that ever comes to a man in this world is a woman's heart.",
    "A dream you dream alone is only a dream. A dream you dream together is reality.",
    "You had me at hello.",
    "Love is a song that never ends.",
    "For the two of us, home isn't a place. It is a person. And we are finally home.",
    "The best and most beautiful things in this world cannot be seen or even heard—they must be felt with the heart",
    "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.",
    "At the touch of love everyone becomes a poet.",
    "Nobody has ever measured, not even poets, how much the heart can hold.",
    "Tell me who admires you loves you, and I will tell you who you are.",
    "Who, being loved, is poor?",
    "Love is the only gold.",
    "For small creatures such as we the vastness is bearable only through love.",
    "The love we give away is the only love we keep.",
    "Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation.",
    "There is always some madness in love. But there is also always some reason in madness."

]

export {quotes};